const navToggle=document.querySelector('.nav-toggle');
const nav=document.querySelector('.main-nav');
if(navToggle&&nav){navToggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');navToggle.setAttribute('aria-expanded',String(open));});}

(function restoreHomeLinksAndPainting(){
  const links={live:'https://bmclive.balconymusicclub.com/',home:'https://www.balconymusicclub.com/',shows:'https://shows.balconymusicclub.com/',host:'https://www.balconymusicclub.com/host-your-event',store:'https://www.balconymusicclub.com/store',jazzycat:'https://www.balconymusicclub.com/ask-jazzycat/',app:'https://app.balconymusicclub.com/'};
  const painting='bmc_homepage_build/assets/gallery-4.jpg?v=live-tonight-bg-restore-20260705';
  function setLink(el,href,target){if(!el)return;el.href=href;el.target=target||'_top';if(el.target==='_blank')el.rel='noopener noreferrer';else el.removeAttribute('rel');}
  function placeBmcLiveFirst(){const mainNav=document.querySelector('.main-nav');if(!mainNav)return;mainNav.querySelectorAll('a').forEach((a)=>{const label=(a.textContent||'').trim().toLowerCase();if(label==='bmc live'||a.href===links.live)a.remove();});const live=document.createElement('a');live.textContent='BMC Live';setLink(live,links.live);mainNav.insertBefore(live,mainNav.firstChild);}
  function restorePainting(){const box=document.querySelector('.stage-photo');if(!box)return;box.dataset.bandPhotoWire='false';box.classList.remove('bmc-stage-band-wire');box.setAttribute('aria-label','Balcony Music Club stage mural painting');box.textContent='';box.style.height=window.innerWidth<=760?'62px':'118px';box.style.border='1px solid rgba(226,58,191,.7)';box.style.backgroundColor='#120728';box.style.backgroundImage='linear-gradient(90deg,rgba(18,7,38,.10),rgba(18,7,38,.26)),url("'+painting+'")';box.style.backgroundSize='cover';box.style.backgroundPosition='center 48%';box.style.backgroundRepeat='no-repeat';box.style.overflow='hidden';}
  function fitHome(){let style=document.getElementById('bmc-homepage-fit-restore');if(!style){style=document.createElement('style');style.id='bmc-homepage-fit-restore';document.head.appendChild(style);}style.textContent='html,body{width:100%!important;height:100%!important;margin:0!important;overflow:hidden!important}.bmc-home-radio,.site-footer,.dashboard,.hero-buttons [data-bmc-radio-trigger]{display:none!important}.site-header{position:relative!important;top:auto!important;width:min(1680px,calc(100vw - 36px))!important;margin-top:10px!important;padding:8px 14px!important}.brand img{width:clamp(224px,18vw,350px)!important;max-height:98px!important;object-fit:contain!important;image-rendering:auto!important}main#home{min-height:0!important;overflow:visible!important}.hero.shell{width:min(1680px,calc(100vw - 42px))!important;max-width:none!important}.hero{min-height:660px!important;padding-top:clamp(16px,2.3vh,34px)!important;padding-bottom:172px!important;align-items:center!important;overflow:visible!important}.stage-photo{height:118px!important;background-image:linear-gradient(90deg,rgba(18,7,38,.10),rgba(18,7,38,.26)),url("bmc_homepage_build/assets/gallery-4.jpg?v=live-tonight-css-restore")!important;background-size:cover!important;background-position:center 48%!important;background-repeat:no-repeat!important}.live-card{padding:20px!important}.live-card .genre{font-size:16px!important;line-height:1.28!important}.live-card .set-times{margin-bottom:14px!important}.live-card .set-times div{padding:8px 0!important}.jazzycat-band{bottom:38px!important;min-height:142px!important;padding:12px 20px 16px!important;align-items:center!important;overflow:visible!important}.cat-march{height:116px!important;overflow:visible!important}.cat{height:clamp(82px,8vw,116px)!important}@media(max-width:760px){body{min-height:1080px!important}.header-actions{display:none!important}.hero.shell{display:grid!important;grid-template-columns:1fr!important;grid-template-areas:"copy" "cats" "live"!important;gap:12px!important;height:auto!important;padding-top:12px!important;padding-bottom:58px!important}.hero-copy{grid-area:copy!important}.live-card{grid-area:live!important;padding:12px!important;max-width:650px!important;width:100%!important}.stage-photo{height:62px!important}.jazzycat-band{grid-area:cats!important;position:relative!important;bottom:auto!important;grid-template-columns:.92fr 1.08fr!important;min-height:84px!important;margin:2px 0 0!important;padding:10px 12px!important}.cat-march{height:68px!important;justify-content:flex-end!important}.cat{height:54px!important;margin-left:-10px!important}}';}
  function wire(){setLink(document.querySelector('.brand'),links.home);placeBmcLiveFirst();restorePainting();document.querySelectorAll('.main-nav a').forEach((a)=>{const label=(a.textContent||'').trim().toLowerCase();if(label==='bmc live')setLink(a,links.live);if(label==='home')setLink(a,links.home);if(label==='shows')setLink(a,links.shows);if(label==='host your event')setLink(a,links.host);if(label==='store')setLink(a,links.store);if(label==='ask jazzycat')setLink(a,links.jazzycat);});document.querySelectorAll('.hero-buttons a,.live-card a').forEach((a)=>{const label=(a.textContent||'').toLowerCase();if(label.includes('schedule')||label.includes('shows'))setLink(a,links.shows);});document.querySelectorAll('.header-actions a').forEach((a)=>{const label=(a.textContent||a.getAttribute('aria-label')||'').toLowerCase();if(label.includes('app'))setLink(a,links.app,'_blank');});}
  function run(){fitHome();wire();setTimeout(wire,250);setTimeout(wire,1000);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();
